// Generated by gencpp from file crazyswarm/GenericLogData.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_GENERICLOGDATA_H
#define CRAZYSWARM_MESSAGE_GENERICLOGDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace crazyswarm
{
template <class ContainerAllocator>
struct GenericLogData_
{
  typedef GenericLogData_<ContainerAllocator> Type;

  GenericLogData_()
    : header()
    , values()  {
    }
  GenericLogData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::crazyswarm::GenericLogData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyswarm::GenericLogData_<ContainerAllocator> const> ConstPtr;

}; // struct GenericLogData_

typedef ::crazyswarm::GenericLogData_<std::allocator<void> > GenericLogData;

typedef boost::shared_ptr< ::crazyswarm::GenericLogData > GenericLogDataPtr;
typedef boost::shared_ptr< ::crazyswarm::GenericLogData const> GenericLogDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyswarm::GenericLogData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyswarm::GenericLogData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyswarm::GenericLogData_<ContainerAllocator1> & lhs, const ::crazyswarm::GenericLogData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyswarm::GenericLogData_<ContainerAllocator1> & lhs, const ::crazyswarm::GenericLogData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyswarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::GenericLogData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::GenericLogData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::GenericLogData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::GenericLogData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::GenericLogData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::GenericLogData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyswarm::GenericLogData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfa79f36371fee74e53d96afde61049b";
  }

  static const char* value(const ::crazyswarm::GenericLogData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfa79f36371fee74ULL;
  static const uint64_t static_value2 = 0xe53d96afde61049bULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyswarm::GenericLogData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyswarm/GenericLogData";
  }

  static const char* value(const ::crazyswarm::GenericLogData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyswarm::GenericLogData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] values\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::crazyswarm::GenericLogData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyswarm::GenericLogData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenericLogData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyswarm::GenericLogData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyswarm::GenericLogData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_GENERICLOGDATA_H
