// Generated by gencpp from file crazyswarm/GoTo.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_GOTO_H
#define CRAZYSWARM_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <crazyswarm/GoToRequest.h>
#include <crazyswarm/GoToResponse.h>


namespace crazyswarm
{

struct GoTo
{

typedef GoToRequest Request;
typedef GoToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoTo
} // namespace crazyswarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyswarm::GoTo > {
  static const char* value()
  {
    return "82856b48a972d6af023d961a655bcf75";
  }

  static const char* value(const ::crazyswarm::GoTo&) { return value(); }
};

template<>
struct DataType< ::crazyswarm::GoTo > {
  static const char* value()
  {
    return "crazyswarm/GoTo";
  }

  static const char* value(const ::crazyswarm::GoTo&) { return value(); }
};


// service_traits::MD5Sum< ::crazyswarm::GoToRequest> should match
// service_traits::MD5Sum< ::crazyswarm::GoTo >
template<>
struct MD5Sum< ::crazyswarm::GoToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::GoTo >::value();
  }
  static const char* value(const ::crazyswarm::GoToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::GoToRequest> should match
// service_traits::DataType< ::crazyswarm::GoTo >
template<>
struct DataType< ::crazyswarm::GoToRequest>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::GoTo >::value();
  }
  static const char* value(const ::crazyswarm::GoToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyswarm::GoToResponse> should match
// service_traits::MD5Sum< ::crazyswarm::GoTo >
template<>
struct MD5Sum< ::crazyswarm::GoToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::GoTo >::value();
  }
  static const char* value(const ::crazyswarm::GoToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::GoToResponse> should match
// service_traits::DataType< ::crazyswarm::GoTo >
template<>
struct DataType< ::crazyswarm::GoToResponse>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::GoTo >::value();
  }
  static const char* value(const ::crazyswarm::GoToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_GOTO_H
