// Generated by gencpp from file crazyswarm/GoToResponse.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_GOTORESPONSE_H
#define CRAZYSWARM_MESSAGE_GOTORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyswarm
{
template <class ContainerAllocator>
struct GoToResponse_
{
  typedef GoToResponse_<ContainerAllocator> Type;

  GoToResponse_()
    {
    }
  GoToResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::crazyswarm::GoToResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyswarm::GoToResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToResponse_

typedef ::crazyswarm::GoToResponse_<std::allocator<void> > GoToResponse;

typedef boost::shared_ptr< ::crazyswarm::GoToResponse > GoToResponsePtr;
typedef boost::shared_ptr< ::crazyswarm::GoToResponse const> GoToResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyswarm::GoToResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyswarm::GoToResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace crazyswarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::GoToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::GoToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::GoToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::GoToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::GoToResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::GoToResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyswarm::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::crazyswarm::GoToResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyswarm::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyswarm/GoToResponse";
  }

  static const char* value(const ::crazyswarm::GoToResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyswarm::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::crazyswarm::GoToResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyswarm::GoToResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyswarm::GoToResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::crazyswarm::GoToResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_GOTORESPONSE_H
