// Generated by gencpp from file crazyswarm/Land.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_LAND_H
#define CRAZYSWARM_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <crazyswarm/LandRequest.h>
#include <crazyswarm/LandResponse.h>


namespace crazyswarm
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace crazyswarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyswarm::Land > {
  static const char* value()
  {
    return "b665b6c83a196e4774268cc26329b159";
  }

  static const char* value(const ::crazyswarm::Land&) { return value(); }
};

template<>
struct DataType< ::crazyswarm::Land > {
  static const char* value()
  {
    return "crazyswarm/Land";
  }

  static const char* value(const ::crazyswarm::Land&) { return value(); }
};


// service_traits::MD5Sum< ::crazyswarm::LandRequest> should match
// service_traits::MD5Sum< ::crazyswarm::Land >
template<>
struct MD5Sum< ::crazyswarm::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::Land >::value();
  }
  static const char* value(const ::crazyswarm::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::LandRequest> should match
// service_traits::DataType< ::crazyswarm::Land >
template<>
struct DataType< ::crazyswarm::LandRequest>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::Land >::value();
  }
  static const char* value(const ::crazyswarm::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyswarm::LandResponse> should match
// service_traits::MD5Sum< ::crazyswarm::Land >
template<>
struct MD5Sum< ::crazyswarm::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::Land >::value();
  }
  static const char* value(const ::crazyswarm::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::LandResponse> should match
// service_traits::DataType< ::crazyswarm::Land >
template<>
struct DataType< ::crazyswarm::LandResponse>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::Land >::value();
  }
  static const char* value(const ::crazyswarm::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_LAND_H
