// Generated by gencpp from file crazyswarm/SetGroupMask.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_SETGROUPMASK_H
#define CRAZYSWARM_MESSAGE_SETGROUPMASK_H

#include <ros/service_traits.h>


#include <crazyswarm/SetGroupMaskRequest.h>
#include <crazyswarm/SetGroupMaskResponse.h>


namespace crazyswarm
{

struct SetGroupMask
{

typedef SetGroupMaskRequest Request;
typedef SetGroupMaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGroupMask
} // namespace crazyswarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyswarm::SetGroupMask > {
  static const char* value()
  {
    return "d44d7e9aa94d069ed5834dbd7329e1bb";
  }

  static const char* value(const ::crazyswarm::SetGroupMask&) { return value(); }
};

template<>
struct DataType< ::crazyswarm::SetGroupMask > {
  static const char* value()
  {
    return "crazyswarm/SetGroupMask";
  }

  static const char* value(const ::crazyswarm::SetGroupMask&) { return value(); }
};


// service_traits::MD5Sum< ::crazyswarm::SetGroupMaskRequest> should match
// service_traits::MD5Sum< ::crazyswarm::SetGroupMask >
template<>
struct MD5Sum< ::crazyswarm::SetGroupMaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::SetGroupMask >::value();
  }
  static const char* value(const ::crazyswarm::SetGroupMaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::SetGroupMaskRequest> should match
// service_traits::DataType< ::crazyswarm::SetGroupMask >
template<>
struct DataType< ::crazyswarm::SetGroupMaskRequest>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::SetGroupMask >::value();
  }
  static const char* value(const ::crazyswarm::SetGroupMaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyswarm::SetGroupMaskResponse> should match
// service_traits::MD5Sum< ::crazyswarm::SetGroupMask >
template<>
struct MD5Sum< ::crazyswarm::SetGroupMaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::SetGroupMask >::value();
  }
  static const char* value(const ::crazyswarm::SetGroupMaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::SetGroupMaskResponse> should match
// service_traits::DataType< ::crazyswarm::SetGroupMask >
template<>
struct DataType< ::crazyswarm::SetGroupMaskResponse>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::SetGroupMask >::value();
  }
  static const char* value(const ::crazyswarm::SetGroupMaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_SETGROUPMASK_H
