// Generated by gencpp from file crazyswarm/StartTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_STARTTRAJECTORYREQUEST_H
#define CRAZYSWARM_MESSAGE_STARTTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyswarm
{
template <class ContainerAllocator>
struct StartTrajectoryRequest_
{
  typedef StartTrajectoryRequest_<ContainerAllocator> Type;

  StartTrajectoryRequest_()
    : groupMask(0)
    , trajectoryId(0)
    , timescale(0.0)
    , reversed(false)
    , relative(false)  {
    }
  StartTrajectoryRequest_(const ContainerAllocator& _alloc)
    : groupMask(0)
    , trajectoryId(0)
    , timescale(0.0)
    , reversed(false)
    , relative(false)  {
  (void)_alloc;
    }



   typedef uint8_t _groupMask_type;
  _groupMask_type groupMask;

   typedef uint8_t _trajectoryId_type;
  _trajectoryId_type trajectoryId;

   typedef float _timescale_type;
  _timescale_type timescale;

   typedef uint8_t _reversed_type;
  _reversed_type reversed;

   typedef uint8_t _relative_type;
  _relative_type relative;





  typedef boost::shared_ptr< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartTrajectoryRequest_

typedef ::crazyswarm::StartTrajectoryRequest_<std::allocator<void> > StartTrajectoryRequest;

typedef boost::shared_ptr< ::crazyswarm::StartTrajectoryRequest > StartTrajectoryRequestPtr;
typedef boost::shared_ptr< ::crazyswarm::StartTrajectoryRequest const> StartTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator1> & lhs, const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.groupMask == rhs.groupMask &&
    lhs.trajectoryId == rhs.trajectoryId &&
    lhs.timescale == rhs.timescale &&
    lhs.reversed == rhs.reversed &&
    lhs.relative == rhs.relative;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator1> & lhs, const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyswarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74e2cf5224bc82fcc8d9c7dd3865d912";
  }

  static const char* value(const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74e2cf5224bc82fcULL;
  static const uint64_t static_value2 = 0xc8d9c7dd3865d912ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyswarm/StartTrajectoryRequest";
  }

  static const char* value(const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 groupMask\n"
"uint8 trajectoryId\n"
"float32 timescale\n"
"bool reversed\n"
"bool relative\n"
;
  }

  static const char* value(const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.groupMask);
      stream.next(m.trajectoryId);
      stream.next(m.timescale);
      stream.next(m.reversed);
      stream.next(m.relative);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyswarm::StartTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "groupMask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.groupMask);
    s << indent << "trajectoryId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectoryId);
    s << indent << "timescale: ";
    Printer<float>::stream(s, indent + "  ", v.timescale);
    s << indent << "reversed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reversed);
    s << indent << "relative: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relative);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_STARTTRAJECTORYREQUEST_H
