// Generated by gencpp from file crazyswarm/UpdateParams.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_UPDATEPARAMS_H
#define CRAZYSWARM_MESSAGE_UPDATEPARAMS_H

#include <ros/service_traits.h>


#include <crazyswarm/UpdateParamsRequest.h>
#include <crazyswarm/UpdateParamsResponse.h>


namespace crazyswarm
{

struct UpdateParams
{

typedef UpdateParamsRequest Request;
typedef UpdateParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateParams
} // namespace crazyswarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyswarm::UpdateParams > {
  static const char* value()
  {
    return "279e0627eb574ffe8968384218434f5f";
  }

  static const char* value(const ::crazyswarm::UpdateParams&) { return value(); }
};

template<>
struct DataType< ::crazyswarm::UpdateParams > {
  static const char* value()
  {
    return "crazyswarm/UpdateParams";
  }

  static const char* value(const ::crazyswarm::UpdateParams&) { return value(); }
};


// service_traits::MD5Sum< ::crazyswarm::UpdateParamsRequest> should match
// service_traits::MD5Sum< ::crazyswarm::UpdateParams >
template<>
struct MD5Sum< ::crazyswarm::UpdateParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::UpdateParams >::value();
  }
  static const char* value(const ::crazyswarm::UpdateParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::UpdateParamsRequest> should match
// service_traits::DataType< ::crazyswarm::UpdateParams >
template<>
struct DataType< ::crazyswarm::UpdateParamsRequest>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::UpdateParams >::value();
  }
  static const char* value(const ::crazyswarm::UpdateParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyswarm::UpdateParamsResponse> should match
// service_traits::MD5Sum< ::crazyswarm::UpdateParams >
template<>
struct MD5Sum< ::crazyswarm::UpdateParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::UpdateParams >::value();
  }
  static const char* value(const ::crazyswarm::UpdateParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::UpdateParamsResponse> should match
// service_traits::DataType< ::crazyswarm::UpdateParams >
template<>
struct DataType< ::crazyswarm::UpdateParamsResponse>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::UpdateParams >::value();
  }
  static const char* value(const ::crazyswarm::UpdateParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_UPDATEPARAMS_H
