// Generated by gencpp from file crazyswarm/UploadTrajectory.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_UPLOADTRAJECTORY_H
#define CRAZYSWARM_MESSAGE_UPLOADTRAJECTORY_H

#include <ros/service_traits.h>


#include <crazyswarm/UploadTrajectoryRequest.h>
#include <crazyswarm/UploadTrajectoryResponse.h>


namespace crazyswarm
{

struct UploadTrajectory
{

typedef UploadTrajectoryRequest Request;
typedef UploadTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UploadTrajectory
} // namespace crazyswarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyswarm::UploadTrajectory > {
  static const char* value()
  {
    return "becd7733dfdc3d0c93a9064ba651cf17";
  }

  static const char* value(const ::crazyswarm::UploadTrajectory&) { return value(); }
};

template<>
struct DataType< ::crazyswarm::UploadTrajectory > {
  static const char* value()
  {
    return "crazyswarm/UploadTrajectory";
  }

  static const char* value(const ::crazyswarm::UploadTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::crazyswarm::UploadTrajectoryRequest> should match
// service_traits::MD5Sum< ::crazyswarm::UploadTrajectory >
template<>
struct MD5Sum< ::crazyswarm::UploadTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyswarm::UploadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::UploadTrajectoryRequest> should match
// service_traits::DataType< ::crazyswarm::UploadTrajectory >
template<>
struct DataType< ::crazyswarm::UploadTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyswarm::UploadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyswarm::UploadTrajectoryResponse> should match
// service_traits::MD5Sum< ::crazyswarm::UploadTrajectory >
template<>
struct MD5Sum< ::crazyswarm::UploadTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyswarm::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyswarm::UploadTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyswarm::UploadTrajectoryResponse> should match
// service_traits::DataType< ::crazyswarm::UploadTrajectory >
template<>
struct DataType< ::crazyswarm::UploadTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::crazyswarm::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyswarm::UploadTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_UPLOADTRAJECTORY_H
