// Generated by gencpp from file crazyswarm/UploadTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_UPLOADTRAJECTORYREQUEST_H
#define CRAZYSWARM_MESSAGE_UPLOADTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <crazyswarm/TrajectoryPolynomialPiece.h>

namespace crazyswarm
{
template <class ContainerAllocator>
struct UploadTrajectoryRequest_
{
  typedef UploadTrajectoryRequest_<ContainerAllocator> Type;

  UploadTrajectoryRequest_()
    : trajectoryId(0)
    , pieceOffset(0)
    , pieces()  {
    }
  UploadTrajectoryRequest_(const ContainerAllocator& _alloc)
    : trajectoryId(0)
    , pieceOffset(0)
    , pieces(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _trajectoryId_type;
  _trajectoryId_type trajectoryId;

   typedef uint32_t _pieceOffset_type;
  _pieceOffset_type pieceOffset;

   typedef std::vector< ::crazyswarm::TrajectoryPolynomialPiece_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::crazyswarm::TrajectoryPolynomialPiece_<ContainerAllocator> >> _pieces_type;
  _pieces_type pieces;





  typedef boost::shared_ptr< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UploadTrajectoryRequest_

typedef ::crazyswarm::UploadTrajectoryRequest_<std::allocator<void> > UploadTrajectoryRequest;

typedef boost::shared_ptr< ::crazyswarm::UploadTrajectoryRequest > UploadTrajectoryRequestPtr;
typedef boost::shared_ptr< ::crazyswarm::UploadTrajectoryRequest const> UploadTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator1> & lhs, const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.trajectoryId == rhs.trajectoryId &&
    lhs.pieceOffset == rhs.pieceOffset &&
    lhs.pieces == rhs.pieces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator1> & lhs, const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyswarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "becd7733dfdc3d0c93a9064ba651cf17";
  }

  static const char* value(const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbecd7733dfdc3d0cULL;
  static const uint64_t static_value2 = 0x93a9064ba651cf17ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyswarm/UploadTrajectoryRequest";
  }

  static const char* value(const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 trajectoryId\n"
"uint32 pieceOffset\n"
"TrajectoryPolynomialPiece[] pieces\n"
"\n"
"================================================================================\n"
"MSG: crazyswarm/TrajectoryPolynomialPiece\n"
"#\n"
"\n"
"float32[] poly_x\n"
"float32[] poly_y\n"
"float32[] poly_z\n"
"float32[] poly_yaw\n"
"duration duration\n"
;
  }

  static const char* value(const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectoryId);
      stream.next(m.pieceOffset);
      stream.next(m.pieces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UploadTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyswarm::UploadTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "trajectoryId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectoryId);
    s << indent << "pieceOffset: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pieceOffset);
    s << indent << "pieces[]" << std::endl;
    for (size_t i = 0; i < v.pieces.size(); ++i)
    {
      s << indent << "  pieces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::crazyswarm::TrajectoryPolynomialPiece_<ContainerAllocator> >::stream(s, indent + "    ", v.pieces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_UPLOADTRAJECTORYREQUEST_H
