language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      # osx_image: xcode7.2

# dist: xenial

# os:
  # - linux
  # - osx

# compiler:
#   - gcc
#   - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

# additional linux dependencies
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libboost-program-options-dev

# # additional mac dependencies
# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb; fi

script: make
